# Continuous Integration config
# travis-ci.org
#
# see http://about.travis-ci.org/docs/user/build-configuration/
#

language: python
python:
  - "3.4"
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y lame vorbis-tools faac faad flac mpg123

# command to install dependencies
install:
  - "pip install coveralls"
  - "if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pip install unittest2 --use-mirrors; fi"

# output installed codecs
before_script:
  ./audiotranscoder --codecs

# command to run tests
script:
  coverage run --source=audiotranscode $(command -v nosetests)

after_success:
  coveralls

